project:
  type: website
  output-dir: docs
  preview: 
    port: 1200
    browser: true

website:
  title: "CEA"
  back-to-top-navigation: true
  search: true
  navbar: 
    background: white
    search: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Story Map"
        href: storymap.qmd
      - text: "Dashboard"
        href: dashboard.qmd
  # page-footer: |
  #   ![](/assets/logos/uhm-logo.png){width=30%}
  #   <br><br>
        
format:
  html:
    theme: litera
    toc-location: left
    toc: true
    page-layout: full
    link-external-newwindow: true
    code-overflow: wrap
    code-annotations: hover
    # margin-header: |
    #   ![](/assets/logos/uhm-logo.png) 

execute:
  message: false
  warning: false
